server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql-database-grupo1.ckiqtgesdyez.us-east-1.rds.amazonaws.com:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: grupo1
    password: grupo1admin